repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        arg: ["--config=setup.cfg"]
        language: python
        types: [python]