version: '3'
services:
  postgres:
    image: postgres:13.3
    env_file: ./env/postgres/.env
    ports:
      - 5432:5432
    restart: on-failure

  repka_admin:
    build: ./repka_admin
    env_file:
      - ./env/repka_admin/.env
    volumes:
      - static_volume:/opt/application/static/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: on-failure

  # app:
  #   container_name: repka_frontend_dc
  #   image: repka-frontend-docker
  #   build:
  #     context: /opt/repka_project_frontend/application
  #   ports:
  #     - 8001:8001
  #   depends_on:
  #     - nginx
  #   restart: on-failure

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - static_volume:/opt/application/static/:rw
    depends_on:
      - repka_admin
    ports:
      - 80:80
    restart: on-failure

volumes:
  static_volume:
